name: Build and Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chatbot-ui:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chatbot-ui:cache
        cache-to: type=inline

    - name: Run Tests
      run: docker run ${{ secrets.DOCKER_USERNAME }}/chatbot-ui:latest npm test

