name: Build and Deploy with Supabase DinD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker environment
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chatbot-ui:latest

    - name: Setup Docker Compose
      run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.0.0-beta.6/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose

    - name: Start Supabase with Docker Compose
      run: |
        docker compose -f ./supabase/docker-compose.yml up -d

    - name: Verify Services
      run: |
        docker compose -f ./supabase/docker-compose.yml ps

    - name: Clean up
      if: always()
      run: |
        docker compose -f ./supabase/docker-compose.yml down
