name: Build and Deploy with Supabase DinD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker environment
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for chatbot-ui
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chatbot-ui:latest

    - name: Download and setup Supabase docker-compose
      run: |
        git clone --depth 1 https://github.com/supabase/supabase
        cd supabase/docker
        cp .env.example .env
        # Here you would also configure your .env file as needed

    - name: Start Supabase services using Docker Compose
      run: |
        cd supabase/docker
        docker-compose up -d

    - name: Check services
      run: |
        cd supabase/docker
        docker-compose ps

    - name: Run tests or additional commands
      run: |
        echo "Here you can run tests or any other checks"

    - name: Clean up Supabase services
      if: always()
      run: |
        cd supabase/docker
        docker-compose down
