name: Build and Deploy with Supabase DinD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and setup Supabase docker-compose
      run: |
        git clone --depth 1 https://github.com/supabase/supabase
        cd supabase/docker
        cp .env.example .env
        # Here you would also configure your .env file as needed

    - name: Start Supabase services using Docker Compose
      run: |
        cd supabase/docker
        docker-compose up -d

    - name: Check services
      run: |
        cd supabase/docker
        docker-compose ps

    - name: Run tests or additional commands
      run: |
        echo "Here you can run tests or any other checks"

    - name: Clean up Supabase services
      if: always()
      run: |
        cd supabase/docker
        docker-compose down
