name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chatbot-ui:latest

    - name: Run Supabase locally (for integration tests)
      run: |
        docker pull supabase/supabase
        docker run -d --name supabase -p 8000:8000 supabase/supabase
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    - name: Integration Tests
      run: npm run test-integration
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    - name: Cleanup Supabase Instance
      if: always()
      run: docker rm -f supabase
