name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t chatbot-ui .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Use Environment Files instead of save-state
      - name: Set Docker credentials
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV && echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker tag chatbot-ui ${{ secrets.DOCKER_USERNAME }}/chatbot-ui:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-ui:latest

