name: Update Fork

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Fetch upstream changes
      run: |
        git remote add upstream https://github.com/mckaywrigley/chatbot-ui.git
        git fetch upstream

    - name: Check for new commits in upstream
      id: upstream-check
      run: |
        UPSTREAM_SHA=$(git ls-remote https://github.com/mckaywrigley/chatbot-ui.git refs/heads/main | cut -f 1)
        LOCAL_SHA=$(git rev-parse HEAD)
        if [ "$UPSTREAM_SHA" = "$LOCAL_SHA" ]; then
          echo "No changes in upstream"
          echo "::set-output name=changed::false"
        else
          echo "New changes found in upstream"
          echo "::set-output name=changed::true"
        fi

    - name: Merge upstream changes if there are any
      if: steps.upstream-check.outputs.changed == 'true'
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories
        git push origin main
      continue-on-error: true

    - name: Notify merge failure
      if: failure() && steps.upstream-check.outputs.changed == 'true'
      run: |
        echo "Merge failed, manual intervention required."
        # Add notification or error handling step here, e.g., sending an email or posting to a Slack channel
