name: Update Fork

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Fetch upstream changes
      run: |
        git remote add upstream https://github.com/mckaywrigley/chatbot-ui.git
        git fetch upstream
        git checkout main
        git merge upstream/main

    - name: Push changes to fork
      run: |
        git push origin main

